ImPinker/ImPinker/Controllers/SearchController.cs
using System.Web.Mvc;
using ImBLL;
using ImModel.Dto;
using ImModel.ViewModel;

namespace ImPinker.Controllers
{
    public class SearchController : Controller
    {
        //
        // GET: 搜索，获取首页数据
        public ActionResult Index(SearchDto dto)
        {
            if (dto.PageNum == 0)
            {
                dto.PageNum = 1;
            }
            if (dto.PageCount == 0)
            {
                dto.PageCount = 32;
            }
            dto.IsHighLight = true;
            var searchvm = GetByPage(dto);
            ViewBag.searchVm = searchvm;
            return View();
        }

        /// <summary>
        /// 分页获取数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetNextPage(SearchDto dto)
        {
            var searchvm = GetByPage(dto);
            return PartialView("_Index_Article", searchvm.ArticleList);
        }
        /// <summary>
        /// 搜索，按分页获取数据
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        private SearchResultVm GetByPage(SearchDto dto)
        {
            var searchvm = new SearchResultVm();
            if (string.IsNullOrEmpty(dto.Key) && string.IsNullOrEmpty(dto.Tab)) return searchvm;
            var urlDecode = System.Web.HttpUtility.UrlDecode(dto.Key);
            if (urlDecode != null)
                dto.Key = urlDecode.Replace(" ", ",");  //url解码，去除特殊字符
            searchvm = SolrNetSearchBll.Query(dto.Key, dto.Tab, dto.FacetCompany, dto.FacetTag, dto.FacetDateTime, dto.PageNum, dto.PageCount);
            return searchvm;
        }

        /// <summary>
        /// 首页热门标签分类及文章热门标签页面
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        public ActionResult HotTag(SearchDto dto)
        {
            if (dto.PageNum == 0)
            {
                dto.PageNum = 1;
            }
            if (dto.PageCount == 0)
            {
                dto.PageCount = 32;
            }
            dto.IsHighLight = false;
            var searchvm = SolrNetSearchBll.QueryHotTag(dto.Key, dto.Tab, dto.FacetCompany, dto.FacetTag, dto.FacetDateTime, dto.PageNum, dto.PageCount, false);
            ViewBag.HotTag = dto.Key;
            ViewBag.searchVm = searchvm;
            return View();
        }

    }
}

ImPinker/ImPinker/Controllers/UserCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImBLL;
using ImModel;
using ImModel.ViewModel;
using ImPinker.Filters;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace ImPinker.Controllers
{
    public class UserCenterController : Controller
    {
        private static readonly ArticleBll ArticleBll = new ArticleBll();
        private static readonly UserBll UserBll = new UserBll();
        //个人中心首页
        // GET: /UserCenter/
        [AuthorizationFilter]
        public ActionResult Index()
        {
            var user = UserBll.GetModelByAspNetId(User.Identity.GetUserId());
            var totalCount = 0;
            var articles = ArticleBll.GetMyListByPage(user.Id, 1, 3, out totalCount);
            ViewBag.User = user;
            ViewBag.Articles = articles;
            ViewBag.totalCount = totalCount;
            return View();
        }

        /// <summary>
        /// 账号设置
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult UserSetting()
        {
            var user = UserBll.GetModelByAspNetId(User.Identity.GetUserId());
            ViewBag.User = user;
            return View();
        }
        /// <summary>
        /// 用户修改显示昵称
        /// </summary>
        /// <param name="showname"></param>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult UpdateShowName(string showname)
        {
            var user = UserBll.GetModelByAspNetId(User.Identity.GetUserId());
            if (!string.IsNullOrEmpty(showname))
            {
                user.ShowName = showname;
                var falg = UserBll.Update(user);
                if (falg)
                {
                    return RedirectToAction("UserSetting");
                }
            }
            return View("Index");
        }

        /// <summary>
        /// 文章详情页，该文章作者信息
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult ArticleWriterInfo(ArticleViewModel articleViewModel)
        {
            int totalCount = 0;
            var articleId = articleViewModel.Id;
            var userid = articleViewModel.Userid;
            var user = UserBll.GetModelByCache(Int32.Parse(userid));
            ViewBag.Writer = user;
            return PartialView();
        }

    }
}

ImPinker/ImPinker/Views/Shared/UserCenter_NavPartial.cshtml
@using Microsoft.AspNet.Identity

<!--nav-->
<div class="usercenter-left">
    <ul class="nav nav-fixed" style="top: auto; bottom: 171px;">
        @{
            //var coutrollerName=ViewContext.RouteData.Values["controller"].ToString().ToLower();
            var actionName=ViewContext.RouteData.Values["action"].ToString().ToLower();
        }
        <li @(!string.IsNullOrEmpty(actionName) && actionName.StartsWith("index") ? "class=current" : "") >@Html.ActionLink("个人中心", "Index", "UserCenter")</li>
        <li><a href="/center/fins" class="nav-friend">好友管理</a></li>
        <li><a href="/center/news" class="nav-info">消息中心</a></li>
        <li @(!string.IsNullOrEmpty(actionName) && actionName.StartsWith("myarticles") ? "class=current" : "")>@Html.ActionLink("帖子管理", "MyArticles", "UserCenter")</li>
        <li><a href="/center/drafts">草稿箱</a></li>
        <li><a href="/center/blacklist">黑名单</a></li>
        <li><a href="/center/favorite">收藏管理</a></li>
        <li><a href="/center/setup" target="_blank">账号设置</a></li>
    </ul>
</div>
<!--nav end-->

ImPinker/ImPinker/Views/Shared/_FootPartial.cshtml
<div id="footer">
    <div class="container">
        <div class="left-footer">
            <ul class="about">
                @*<li> @DateTime.Now.Year - 转动科技-MyAutos </li>*@
                <li> @Html.ActionLink("关于车酷", "About", "Home") </li>
                <span class="line"></span>
                <li>@Html.ActionLink("联系我们", "About", "Home")</li>
            </ul>
            <div class="clear"></div>
            <div class="copyright">
                <span>©2016-2017 www.myautos.cn All Rights Reserved</span>
                <span>Beijing MYCARS INTELLIGENCE Co.,Ltd.</span><span>京ICP备125698521639号-1</span><br>
            </div>
        </div>
        <div class="right-footer">
            <img src="/content/image/qrcode_for_gh_7f5be927b079_258.jpg" style="width:155px;height:155px"/>
        </div>
    </div>
</div>

ImPinker/ImPinker/Views/Shared/_HeadPartial.cshtml
<a id="maodian" style="display:block; height:0; width:0; line-height:0; font-size:0"></a>
<div id="header">
    <div class="header-row-1">
        <div class="header-container">
            <div class="header-row-1-col-1">
                @Html.ActionLink("关于车酷", "Index", "Home", null, new { @class = "navbar-right" })
            </div>
            <ul class="header-row-1-col-2">
                <li class="nav-shop" ms-controller="wrap">
                @Html.ActionLink("旅行", "About", "Home")</li>
                <li class="nav-interest">
                    <a href="#">兴趣</a>
                </li>
                <li class="nav-follow"><a href="#">关注的人</a></li>
                <li class="nav-ranklist"><a href="#">排行榜</a></li>
            </ul>
            <div class="header-row-1-col-4">
                <div class="user-info-box">
                    @Html.Partial("_LoginPartial")
                </div>
                @*<a href="#" target="_blank" class="xbshop-btn"><i></i>车库圈子</a>*@
            </div>

            @*<div class="header-row-1-col-3">
                <div class="search-box">
                    <a href="javascript:;" class="search-btn" ></a>
                    <input type="text" id="searchterm" placeholder="乌兰布统冬日自驾游" autocomplete="off">
                    <div class="search-record">
                        <span><em></em><i></i></span>
                        <div class="search-record-box">
                            <ul></ul>
                        </div>
                    </div>
                </div>
            </div>*@
        </div>
    </div>
    <div class="header-row-2">
        <div class="header-container">
            <a class="logo" href="/Home/Index"></a>
            <div>
                <div class="search-container">
                    <input type="text" id="searchinput" placeholder="乌兰布统冬日自驾游">
                    <a class="search-submit-btn">
                        <i class="search-icon"></i>
                        搜索
                    </a>

                </div>
                <ul class="navigator">
                    <li class="followpage"><a href="#">我关注的</a></li>
                    <li class="rankpage"><a href="#">排行榜</a></li>
                    <li class="centerpage" ><a href="#">我的车库</a></li>
                </ul>
            </div>
            <div class="side-bar" style="bottom: 20px; opacity: 1; right: auto;display: none">
                @*<div class="down-app">
                <a href="/html/app.html" target="_blank" class="app">
                    <em>下载客户端</em>
                    <i></i>
                </a>
            </div>*@
                <a href="#maodian" class="go-top">
                    <em>返回顶部</em>
                    <i></i>
                </a>
            </div>
        </div>
    </div>
</div>


<div style="display: none" id="searchKey"></div>
<script type="text/javascript">
    var state = "@Html.Raw(Request.IsAuthenticated)";  //全局变量，标记是否登录
    var LoginState = false;//;
    if (state=="True") {
        LoginState = true;
    } else {
        LoginState = false;
    }
    
    $(document).ready(function () {
        //返回顶部按钮绑定事件
        $(window).scroll(function () {
            var top = $(document).scrollTop();
            if (top > 300) {
                $(".side-bar").fadeIn();
            } else {
                $(".side-bar").fadeOut();
            }
        });
        
        //两个搜索框的事件绑定
        $(".search-btn").click(function () {
            var keyword = $("#searchterm").val();
            search(keyword);
        });
        $(".search-submit-btn").click(function () {
            var keyword = $("#searchinput").val();
            search(keyword);
        });
        //回车
        $(document).keydown(function (event) {
            if (event.keyCode == 13) {
                var keyword = $("#searchinput").val();
                search(keyword);
            }
        });
        //设置搜索框文本
        var keys = $.getUrlParam("key");
        var tabs = $("#tabList a[class='b_yaowen b_twolcur']").text();
        if (keys != null && keys.length > 0) {
            keys = keys.replace("," + tabs, "");
            $("#searchterm").val(keys);
        }
    });

    //搜索
    function search(keyword) {
        //var keyword = $("#searchterm").val();
        var tabStr = $("#tabList a[class='b_yaowen b_twolcur']").text();
        if (keyword != null && keyword.length > 0) {
            window.open("/Search/Index?key=" + keyword + "&tab=" + tabStr,"_blank");
        }
    }
</script>

ImPinker/ImPinker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="icon" type="image/x-icon" href="~/Content/image/120x120.png" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    @Html.Partial("_HeadPartial")
    @RenderBody()
    @Html.Partial("_FootPartial")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/voteAnimation.js"></script>
</body>
</html>

ImPinker/ImPinker/Views/Shared/_NavPartial.cshtml
@using Microsoft.AspNet.Identity

<!--nav-->
<div class="b_nav">
    <div class="b_navcon clearfix">
        <ul class="clearfix" id="nav_chanel">
            <li class="current">
                <a href="http://newcar.fblife.com" class="lan yijia" target="_blank">新车</a>
            </li>
            <li class="">
                <a href="http://guide.fblife.com" class="hong yijia" target="_blank">导购</a>
            </li>
            <li class="">
                <a href="http://drive.fblife.com" class="hui yijia" target="_blank">试驾</a>
            </li>

            <li class="">
                <a href="http://culture.fblife.com" class="lv yijia" target="_blank">文化</a>
            </li>
            <li class="">
                <a href="http://restyle.fblife.com" class="fen yijia" target="_blank">改装</a>
            </li>
            <li class="">
                <a href="http://tour.fblife.com" class="qianlan yijia" target="_blank">旅行</a>
            </li>
            <li class="b_nav_put"><a href="http://rv.fblife.com" class="yijia" target="_blank">房车</a></li>
            <li class="">
                <a href="http://sports.fblife.com/" class="red-hong yijia" target="_blank">赛事</a>
            </li>
            <li class="b_nav_put"><a href="http://car.fblife.com/tuan" class="yijia" target="_blank">团购</a></li>
            <li class="b_nav_put"><a href="http://event.fblife.com" class="yijia" target="_blank">活动</a></li>
            <li class="b_nav_put"><a href="http://photo.fblife.com" class="yijia" target="_blank">图片</a></li>
            <li class="b_nav_teshu mlten">
                <a href="http://carport.fblife.com/" class="yijia" target="_blank">
                    <cite class="car_ku"></cite>
                    <span>车库</span>
                </a>
            </li>
            <li class="b_nav_teshu">
                <a href="http://v.fblife.com" class="yijia" target="_blank">
                    <cite class="o_shipin"></cite>
                    <span>视频</span>
                </a>
            </li>
            <li class="b_nav_teshu">
                <a href="http://bbs.fblife.com/" class="yijia" target="_blank">
                    <cite class="o_shequ"></cite>
                    <span>社区</span>
                </a>
            </li>
            <li class="b_nav_teshu lenxingqiu">
                <a href="http://www.auto.life" class="yijia" target="_blank">
                    <cite class="o_xingqiu"></cite>
                    <span>汽车星球</span>
                </a>
            </li>
            <li class="b_nav_teshu" id="b_nvmore">
                <a href="javascript:void(0)" class="yijia b_navmore">
                    <em class="b_nateduo lt">更多</em>
                    <span class="fb-horn"></span>
                </a>
                <div class="b_hescgd">
                    <a href="http://news.fblife.com" target="_blank">行业</a>
                    <a href="http://tieqi.fblife.com" target="_blank">铁骑</a>
                    <a href="http://use.fblife.com/" target="_blank">用车</a>
                    <a href="http://depreciate.fblife.com" target="_blank">降价</a>
                    <a href="http://culture.fblife.com/channels/jishu.html" target="_blank">技术</a>
                    <a href="http://culture.fblife.com/channels/gongyi.html" target="_blank">公益</a>
                    <a href="http://tour.fblife.com/channels/youji.html" target="_blank">游记</a>
                    <a href="http://tour.fblife.com/channels/sheying.html" target="_blank">摄影</a>
                </div>
            </li>
        </ul>
    </div>
</div>
<!--nav end-->

ImPinker/ImPinker/Views/Shared/_NewArticlePartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
    @Html.AntiForgeryToken()

    <ul class="nav navbar-nav navbar-right">
        <li>
            @Html.ActionLink("你好 " + User.Identity.GetUserName() + "~", "Manage", "Account", routeValues: null, htmlAttributes: new { title = "管理" })
        </li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">注销</a></li>
    </ul>
    }
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("注册", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        <li>@Html.ActionLink("登录", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
    </ul>
}

ImPinker/ImPinker/Views/Shared/_RightPartial.cshtml
<div class="b_jingxuan rt">
    <!--精品栏目---合作专区-->
    <div class="b_jxhd clearfix mt20">
        <div class="b_jxhdlt" id="lanmu_btnone">
            <a href="http://www.fblife.com/list_858.html" class="" target="_blank"><i class="rt"></i>热门搜索</a>
        </div>
    </div>
    <div class="b_jdborder" id="lanmu_list">
        <div class="b_jdhdlist clearfix" style="display: none;">
            <div class="b_jdlpic">
                <a href="http://special.fblife.com/topic/1198/" target="_blank"><span></span><p>【e视界】五十铃mu-X春节自驾游（第6季）</p><img src="http://img10.fblife.com/attachments/20160309/1457495596.jpg.300x200.jpg"></a>
            </div>
            <div class="b_jdliwz clearfix">
                <ul class="b_jdwenzi clearfix">
                    <li><a href="http://special.fblife.com/topic/1192/" target="_blank">【族迹】穿行雪域冰原（第一期）</a></li>
                    <li><a href="http://special.fblife.com/topic/1185/" target="_blank">【妞轱辘试】BRP系列酷炫战场（第1期）</a></li>
                    <li><a href="http://special.fblife.com/topic/1183/" target="_blank">【e视界】相遇初雪 如画坝上（第5季）</a></li>
                </ul>
            </div>
        </div>

        <div class="b_jdhdlist clearfix" style="display: block;">
            <div class="b_jdlpic" style="display:none;">
                <a href="http://news.fblife.com/html/20160111/167141.html" target="_blank"><img src="http://img10.fblife.com/attachments/20160111/1452483382.jpg.300x200.jpg"></a>
            </div>
            <div class="b_jdliwz clearfix">
                <ul class="b_jdwenzi clearfix">
                    <li><a href="http://news.fblife.com/html/20160111/167141.html" target="_blank">依托大数据2015拆车坊年度盛典在京隆重召开</a></li>
                    <li><a href="http://news.fblife.com/html/20160104/166925.html" target="_blank">第三届中国汽车企业社会责任论坛暨益轩奖颁奖</a></li>
                    <li><a href="http://news.fblife.com/html/20151224/166931.html" target="_blank">再谈多元文化潮流下的中国改装</a></li>
                    <li><a href="http://news.fblife.com/html/20151130/166926.html" target="_blank">广州今年没有冬天 PCauto火辣车展报道</a></li>
                    <li><a href="http://news.fblife.com/html/20151124/166929.html" target="_blank">“蓝英”为新媒体营销领潮者点赞</a></li>
                    <li style="border-top:1px #dcdcdc dashed; height:1px; padding-bottom:8px;margin-top:8px; background:none; overflow:hidden;zoom:1;"></li>
                    <li><a href="http://news.fblife.com/html/20151121/166928.html" target="_blank">车讯互联和广东广播电视台汽车·会展频道牵手</a></li>
                    <li><a href="http://news.fblife.com/html/20151121/166927.html" target="_blank">2016网易年度新车总评榜闪耀羊城 别克威朗斩获</a></li>
                    <li><a href="/html/20150519/159830.html" target="_blank">团车网获“行”认证资质 全力打造汽车产业闭环</a></li>
                    <li><a href="/html/20150519/159828.html" target="_blank">2015长安福特杯媒体足球冠军联赛盛大开幕</a></li>
                    <li><a href="http://news.fblife.com/html/20150513/159638.html" target="_blank">从产业走向民生 第二届法兰克福成都汽配展开幕</a></li>
                </ul>
            </div>
        </div>
    </div>
    <!--精品栏目---合作专区 end-->
    <!--大家都爱看---新闻排行-->
    <div class="b_jxhd clearfix mt10" id="paihang_btnone">
        <div class="b_jxhdlt">
            <a href="javascript:void(0)" class="b_jxactive"><i class="rt"></i>大家都爱看</a>
        </div>
    </div>
    <div class="b_jdborder" id="paihang_list">
        <ul class="b_kankan clearfix" style="display:block;">
            <li><cite class="b_kanone"></cite><a href="http://tour.fblife.com/html/20160125/167649.html" target="_blank">穿行雪域冰原 Jeep自由光克什克腾之旅</a></li>
            <li><cite class="b_kantwo"></cite><a href="http://tieqi.fblife.com/html/20160616/173062.html" target="_blank">近乎完美 外媒点评2016款凯旋Explorer XCA</a></li>
            <li><cite class="b_kanthr"></cite><a href="http://drive.fblife.com/html/20160616/173090.html" target="_blank">英雄迟暮 外媒点评2016福特探险者Platinum</a></li>
            <li><cite class="b_kanfour"></cite><a href="http://culture.fblife.com/html/20160620/173259.html" target="_blank">值得收藏 外媒盘点10款经典越野老爷车</a></li>
            <li><cite class="b_kanfive"></cite><a href="http://sports.fblife.com/html/20160618/173084.html" target="_blank">2016 Gobi Rally 中蒙国际越野拉力赛勘路</a></li>
            <li><cite class="b_kansix"></cite><a href="http://culture.fblife.com/html/20160622/172744.html" target="_blank">基础保障 浅谈热管理系统对越野的重要性</a></li>
            <li><cite class="b_kanseven"></cite><a href="http://newcar.fblife.com/html/20160616/173088.html" target="_blank">对标汉兰达 大众CrossBlue量产版谍照曝光</a></li>
            <li><cite class="b_kaneight"></cite><a href="http://restyle.fblife.com/html/20160619/173100.html" target="_blank">德纳如何成为硬派越野车及众多品牌的供应商</a></li>
            <li><cite class="b_kannine"></cite><a href="http://newcar.fblife.com/html/20160618/173135.html" target="_blank">仅有500辆 道奇推出Ram限量版皮卡</a></li>
            <li class="nobor"><cite class="b_kanten"></cite><a href="http://newcar.fblife.com/html/20160616/173089.html" target="_blank">荣威RX5启动预售 2.0T车型预售价17万到19万</a></li>
            <!-- <li class="nobor"><cite class=""></cite><a href="http://newcar.fblife.com/html/20160621/173276.html" target="_blank">Jeep自由侠新车型售价公布 售价19.28万元起</a></li> -->

        </ul>
        <ul class="b_kankan clearfix">
            <li><cite class="b_kanone"></cite><a href="http://sports.fblife.com/html/20160618/173084.html" target="_blank">2016 Gobi Rally 中蒙国际越野拉力赛勘路</a></li>
            <li><cite class="b_kantwo"></cite><a href="http://mp.weixin.qq.com/s?__biz=MjM5MzM0ODk4MQ==&amp;mid=2652597351&amp;idx=1&amp;sn=07915847435c2cea3d84c246fb0b74e5#rd" target="_blank">你个造拖拉机的也配教我造跑车？</a></li>
            <li><cite class="b_kanthr"></cite><a href="http://culture.fblife.com/html/20160620/173259.html" target="_blank">值得收藏 外媒盘点10款经典越野老爷车</a></li>
            <li><cite class="b_kanfour"></cite><a href="http://sports.fblife.com/html/20160620/173170.html" target="_blank">2016中蒙国际越野拉力赛 赛事指南（二）</a></li>
            <li><cite class="b_kanfive"></cite><a href="http://mp.weixin.qq.com/s?__biz=MjM5MzM0ODk4MQ==&amp;mid=2652597416&amp;idx=1&amp;sn=319e3eeefd6ecf94372f3ef4fdf9a166#rd" target="_blank">女性专属 女人玩越野什么样？</a></li>
            <li><cite class="b_kansix"></cite><a href="http://newcar.fblife.com/html/20160616/173089.html" target="_blank">荣威RX5启动预售 2.0T车型预售价17万到19万</a></li>
            <li><cite class="b_kanseven"></cite><a href="http://mp.weixin.qq.com/s?__biz=MjM5MzM0ODk4MQ==&amp;mid=2652597351&amp;idx=2&amp;sn=a487fb2892c2c428460ac463b1cf0f58#rd" target="_blank">越野越美丽 四大美妞探险库布其</a></li>
            <li><cite class="b_kaneight"></cite><a href="http://mp.weixin.qq.com/s?__biz=MjM5MzM0ODk4MQ==&amp;mid=2652597401&amp;idx=1&amp;sn=c4ec2e5e168564416d97bd4a901cef6c#rd" target="_blank">昔日家用SUV佼佼者英雄迟暮？</a></li>
            <li><cite class="b_kannine"></cite><a href="http://mp.weixin.qq.com/s?__biz=MjM5MzM0ODk4MQ==&amp;mid=2652597405&amp;idx=1&amp;sn=a350b563ba5d6e6e59b51e2341ec4c94#rd" target="_blank">新十年 新开始：2016英雄会第一次勘路</a></li>
            <li class="nobor"><cite class="b_kanten"></cite><a href="http://mp.weixin.qq.com/s?__biz=MjM5MzM0ODk4MQ==&amp;mid=2652597416&amp;idx=3&amp;sn=fcef78f1d9c7f4db7d6dd13039684d7b#rd" target="_blank">仅500辆 有钱不一定能买到的皮卡！</a></li>
        </ul>
    </div>
    <!--大家都爱看---新闻排行 end-->
</div>

ImPinker/ImPinker/Views/Shared/_TabListPartial.cshtml
<ul class="topic-label" id="topicLabel">
    <li class="active all"><a href="/Home/Index">每日更新</a></li>

    <li>
        @Html.ActionLink("越野老炮", "HotTag", "Search", new { key = "越野老炮" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("长途自驾游", "HotTag", "Search", new { key = "长途自驾游" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("重度穿越", "HotTag", "Search", new { key = "重度穿越" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("车酷故事", "HotTag", "Search", new { key = "车酷故事" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("达人装备", "HotTag", "Search", new { key = "达人装备" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("酷车改装", "HotTag", "Search", new { key = "酷车改装" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("动手达人", "HotTag", "Search", new { key = "动手达人" }, new { target = "_blank" })
    </li>

    @*<li>
        @Html.ActionLink("新车表错过", "HotTag", "Search", new { key = "新车评测" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("我是老司机", "HotTag", "Search", new { key = "我是老司机" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("探险越野", "HotTag", "Search", new { key = "探险越野" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("房车旅行", "HotTag", "Search", new { key = "房车旅行" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("老车新生", "HotTag", "Search", new { key = "老车新生" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("侃车聊车", "HotTag", "Search", new { key = "侃车聊车" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("航拍", "HotTag", "Search", new { key = "航拍" }, new { target = "_blank" })
    </li>

    <li>
        @Html.ActionLink("酷车社群", "HotTag", "Search", new { key = "酷车社群" }, new { target = "_blank" })
    </li>*@

</ul>