ImPinker/ImPinker/Models/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ImPinker.Models
{
	public class CreateArticleViewModel
	{
		[Required]
		[Display(Name = "标题")]
		public string ArticleName { get; set; }

		[Required]
		[Display(Name = "链接")]
		public string ArticleUrl { get; set; }

		[Display(Name = "推荐理由")]
		public string Description { get; set; }

		[Display(Name = "标签")]
		public string KeyWords { get; set; }
	}
}

ImPinker/ImPinker/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.Globalization;
using System.Web.Mvc;
using Common.AlyOssUtil;
using Common.Utils;
using ImBLL;
using ImModel;
using ImModel.ViewModel;
using ImPinker.Filters;
using ImPinker.Models;
using Microsoft.AspNet.Identity;

namespace ImPinker.Controllers
{
    public class ArticleController : Controller
    {
        private static readonly ArticleBll ArticleBll = new ArticleBll();
        private static readonly UserBll UserBll = new UserBll();

        /// <summary>
        /// 文章详情页。爬虫抓取到的文章,即userid=2的文章。用户收藏的文章直接跳转到原始页面
        /// </summary>
        /// <param name="id">文章id：travels_id  或者  id</param>
        /// <returns></returns>
        public ActionResult Index(string id)
        {
            var vm = new ArticleViewModel();
            var idStr = id;
            long idInt;
            if (!id.StartsWith("travels_"))
            {
                idStr = "travels_" + id;
            }
            long.TryParse(idStr.Replace("travels_", ""), out idInt);
            try
            {
                vm = SolrNetSearchBll.GetArticleById(idStr);
            }
            catch (Exception e)
            {
                LogHelper.Instance.Error("solr服务未启动:" + e);
            }
            if (vm == null || string.IsNullOrEmpty(vm.Content))
            {
                vm = ArticleBll.GetModelWithContent(idInt);
            }
            vm.Id = idInt.ToString(CultureInfo.InvariantCulture);
            ViewBag.Article = vm;
            return View("Index");
        }

        /// <summary>
        /// 文章详情页，右侧相关文章推荐
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult RelativeArticle(ArticleViewModel articleViewModel)
        {
            var list = new List<ArticleViewModel>();
            if (!string.IsNullOrEmpty(articleViewModel.KeyWords))
            {
                try
                {
                    list = SolrNetSearchBll.QueryArticleByKeyword(articleViewModel.KeyWords, 1, 5).ArticleList;
                }
                catch (Exception e)
                {
                    LogHelper.Instance.Warn("lalalla89898989989898------------:" + e);
                }

            }
            ViewBag.RelativeArticle = list;
            return PartialView();
        }

        /// <summary>
        /// 我的文章
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult MyArticle(int? pageIndex, int? pageCount)
        {
            var pageNum = (int)(pageIndex > 0 ? pageIndex : 1);
            var pagecount = (int)(pageCount > 0 ? pageCount : 9);
            var userId = UserBll.GetModelByAspNetId(User.Identity.GetUserId()).Id;
            int totalCount;
            var articles = ArticleBll.GetMyListByPage(userId, pageNum, pagecount, out totalCount);
            ViewBag.pageIndex = pageNum;
            ViewBag.pageCount = pagecount;
            ViewBag.totalCount = totalCount;
            ViewBag.Articles = articles;
            return View();
        }

        #region 用户收藏网络连接相关操作
        //
        // 添加收藏
        [AuthorizationFilter]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// 添加收藏
        /// </summary>
        /// <param name="createArticleVm"></param>
        /// <returns></returns>
        [AuthorizationFilter]
        [HttpPost]
        public ActionResult Create(CreateArticleViewModel createArticleVm)
        {
            var article = new Article
            {
                Url = createArticleVm.ArticleUrl,
                ArticleName = createArticleVm.ArticleName,
                Description = createArticleVm.Description,
                KeyWords = createArticleVm.KeyWords,
                UserId = UserBll.GetModelByAspNetId(User.Identity.GetUserId()).Id,
                State = (int)ArticleStateEnum.BeCheck,   //待审核状态
                CreateTime = DateTime.Now,
                UpdateTime = DateTime.Now,
                Company = ""
            };
            //审核通过后添加索引
            ArticleBll.Add(article);
            return RedirectToAction("MyArticle");

        }

        //
        // GET: /Article/Edit/5
        [AuthorizationFilter]
        public ActionResult Edit(int id)
        {
            return RedirectToAction("Index");
        }

        //
        // POST: /Article/Edit/5
        [AuthorizationFilter]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /Article/Delete/5
        [AuthorizationFilter]
        public ActionResult Delete(int id)
        {
            return RedirectToAction("Index");
        }

        //
        // POST: /Article/Delete/5
        [AuthorizationFilter]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region 用户发帖子相关操作
        /// <summary>
        /// 发新帖子
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult CreateThread()
        {
            return View();
        }

        /// <summary>
        /// 发新帖子
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateThread(CreateThreadVm model)
        {
            if (string.IsNullOrEmpty(model.Content) || string.IsNullOrEmpty(model.ArticleName))
            {
                AddErrors(IdentityResult.Failed("不能为空"));
                return View(model);
            }
            if (!string.IsNullOrEmpty(model.Coverimage))
            {
                var sourcepath = Server.MapPath("/") + model.Coverimage;
                string ImgUrlformat = "articlefirstimg/{0}/{1}_{2}.jpg";
                var coverimage = string.Format(ImgUrlformat, DateTime.Now.ToString("yyyyMMdd"), UserBll.GetModelByAspNetId(User.Identity.GetUserId()).Id, DateTime.Now.Ticks);

                //缩放
                ImageUtils.ThumbnailImage(sourcepath, sourcepath, 360, 240, ImageFormat.Jpeg);
                string buckeyName = "myautos";
                var ossSucess = ObjectOperate.UploadImage(buckeyName, sourcepath, coverimage, 1024);
                if (ossSucess)
                {
                    var vm = new CreateThreadVm
                    {
                        ArticleName = model.ArticleName,
                        Content = model.Content,
                        Userid = UserBll.GetModelByAspNetId(User.Identity.GetUserId()).Id,
                        Coverimage = coverimage,
                        Keywords = "",
                        Description = "",
                        Createtime = DateTime.Now,
                        Updatetime = DateTime.Now,
                        State = ArticleStateEnum.BeCheck
                    };
                    var flag = ArticleBll.AddThread(vm);
                    if (flag)
                    {
                        return RedirectToAction("MyArticle");
                    }
                }
            }
            AddErrors(IdentityResult.Failed("有错误"));
            return View(model);
        }

        /// <summary>
        /// 修改帖子
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult UpdateThread(int articleId)
        {
            var userid = UserBll.GetModelByAspNetId(User.Identity.GetUserId()).Id;
            var article = ArticleBll.GetModelByCache(articleId);
            var snap = new ArticleSnapsBll().GetModel(articleId);
            if (article != null && article.UserId == userid)
            {
                ViewBag.ArticleContent = snap.Content.Replace("\"", "'");
                ViewBag.Article = article;
                return View();
            }
            ViewBag.Article = null;
            ViewBag.ArticleContent = "";
            return View();
        }

        /// <summary>
        /// 修改帖子
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdateThread(CreateThreadVm model)
        {
            var userid = UserBll.GetModelByAspNetId(User.Identity.GetUserId()).Id;

            if (string.IsNullOrEmpty(model.Content) || string.IsNullOrEmpty(model.ArticleName))
            {
                AddErrors(IdentityResult.Failed("不能为空"));
                return View(model);
            }
            if (!string.IsNullOrEmpty(model.Coverimage))
            {
                var coverimage = model.Coverimage;
                if (!model.Coverimage.StartsWith("articlefirstimg/"))
                {
                    var sourcepath = Server.MapPath("/") + model.Coverimage;
                    string ImgUrlformat = "articlefirstimg/{0}/{1}_{2}.jpg";
                    coverimage = string.Format(ImgUrlformat, DateTime.Now.ToString("yyyyMMdd"), UserBll.GetModelByAspNetId(User.Identity.GetUserId()).Id, DateTime.Now.Ticks);

                    //缩放
                    ImageUtils.ThumbnailImage(sourcepath, sourcepath, 360, 240, ImageFormat.Jpeg);
                    string buckeyName = "myautos";
                    ObjectOperate.UploadImage(buckeyName, sourcepath, coverimage, 200);
                }
                var article = ArticleBll.GetModelByCache(model.ArticleId);

ImPinker/ImPinker/Controllers/UserCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImBLL;
using ImModel;
using ImModel.ViewModel;
using ImPinker.Filters;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace ImPinker.Controllers
{
    public class UserCenterController : Controller
    {
        private static readonly ArticleBll ArticleBll = new ArticleBll();
        private static readonly UserBll UserBll = new UserBll();
        //个人中心首页
        // GET: /UserCenter/
        [AuthorizationFilter]
        public ActionResult Index()
        {
            var user = UserBll.GetModelByAspNetId(User.Identity.GetUserId());
            var totalCount = 0;
            var articles = ArticleBll.GetMyListByPage(user.Id, 1, 3, out totalCount);
            ViewBag.User = user;
            ViewBag.Articles = articles;
            ViewBag.totalCount = totalCount;
            return View();
        }

        /// <summary>
        /// 账号设置
        /// </summary>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult UserSetting()
        {
            var user = UserBll.GetModelByAspNetId(User.Identity.GetUserId());
            ViewBag.User = user;
            return View();
        }
        /// <summary>
        /// 用户修改显示昵称
        /// </summary>
        /// <param name="showname"></param>
        /// <returns></returns>
        [AuthorizationFilter]
        public ActionResult UpdateShowName(string showname)
        {
            var user = UserBll.GetModelByAspNetId(User.Identity.GetUserId());
            if (!string.IsNullOrEmpty(showname))
            {
                user.ShowName = showname;
                var falg = UserBll.Update(user);
                if (falg)
                {
                    return RedirectToAction("UserSetting");
                }
            }
            return View("Index");
        }

        /// <summary>
        /// 文章详情页，该文章作者信息
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult ArticleWriterInfo(ArticleViewModel articleViewModel)
        {
            int totalCount = 0;
            var articleId = articleViewModel.Id;
            var userid = articleViewModel.Userid;
            var user = UserBll.GetModelByCache(Int32.Parse(userid));
            ViewBag.Writer = user;
            return PartialView();
        }

    }
}

ImPinker/ImPinker/Views/Article/Create.cshtml
@model ImPinker.Models.CreateArticleViewModel
@{
    ViewBag.Title = "Create";
}

<h2>添加链接</h2>

@using (Html.BeginForm("Create", "Article", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>创建新帐户。</h4>
    <hr />
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(m => m.ArticleUrl, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ArticleUrl, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ArticleName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ArticleName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.KeyWords, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.KeyWords, new { @class = "form-control",placeholder="关键字用逗号隔开" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control", })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="添加" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ImPinker/ImPinker/Views/Article/CreateThread.cshtml
@model dynamic

@{
    ViewBag.Title = "发新贴";

    <link href="~/Content/thread.css" rel="stylesheet" />
    <link href="~/Scripts/webUpload/webuploader.css" rel="stylesheet" />
    <script src="~/Scripts/webUpload/webuploader.html5only.js"></script>
}

<div id="container">
    <h5 class="crumb"><em>当前位置：</em><a href="/index">首页</a>&gt;<a href="../">话题列表</a>&gt;阅读话题</h5>
    @using (Html.BeginForm("CreateThread", "Article", FormMethod.Post))
    {
        <input type="text" name="ArticleName" placeholder="请输入标题" id="threadName" style="font-size: 24px; padding: 20px ; margin-bottom: 30px; width: 100%; " />
        <div class="small-topic-article" style="padding: 0">
            <script id="contain" name="Content" type="text/plain" style="width: 100%; height: 800px;">
            </script>
        </div>
        <div id="uploader" class="wu-example">
            <!--baiduUploader 上传图片-->
            <div class="btns">
                <div id="picker">设置封面图</div>
                @*<button id="ctlBtn" onclick="return uploadImage()" class="btn btn-default">开始上传</button>*@
            </div>
            <div id="thelist" class="uploader-list"></div>
        </div>
        <br />
        <img id="preview180" src="" style="width: 300px; height: 300px" />
        <input type="hidden" name="Coverimage" id="imgPath" />
        <hr />
        @Html.ValidationSummary()
        <div class="topic-list">
            <input id="btn_publish" type="submit" style=" background: #2175d0; clear: both; display: block; width: 1100px; line-height: 30px; font-size: 14px; color: #fff;  border-radius: 5px; text-align: center; margin: 10px auto; " value="发布" />
        </div>
    }

</div>

@section scripts
{
    <script src="/UeEditer/ueditor.config.js"></script>
    <script src="/UeEditer/ueditor.all.js"></script>
    <script src="/UeEditer/ueditor.parse.js"></script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="/UeEditer/lang/zh-cn/zh-cn.js"></script>
<script src="~/Scripts/webUpload/uploadImg.js"></script>
    <script type="text/javascript">
        //发布帖子
        $(document).ready(function () {
            var ue = UE.getEditor('contain');
            $("#btn_publish").bind("click", function () {
                var flag = ue.hasContents();
                if (flag) {
                    var content = ue.getContent();
                    var articleName = $("#threadName").val();
                    return true;
                    $.ajax({
                        url: "/Article/CreateThread",
                        type: "post",
                        data: { name: articleName, content: content },
                        success: function (data) {
                            alert("bingo！");
                        },
                        error: function (data) {
                            alert(data);
                        }
                    });
                }
            });
        });

        
        
    </script>
}

ImPinker/ImPinker/Views/Article/Index.cshtml
@using ImModel.ViewModel

@{
    var article = (ArticleViewModel)ViewBag.Article;
    ViewBag.Title = article.ArticleName;
    <link href="~/Content/thread.css" rel="stylesheet" />
    <link href="~/Content/player.css" rel="stylesheet" />
    <style type="text/css">
        img {
            max-width: 100%
        }
    </style>
}
@Html.Partial("_TabListPartial")

<div id="container">
    <div class="thread-main">
        <!-- 文章主体 -->
        <div class="article">
            <input type="hidden" id="articleId" value="@article.Id">
            <h2>
                <!-- 是否精华 -->
                <i class="essence-mark"></i>
                @article.ArticleName
            </h2>
            <div class="thread-info">
                <div class="interest">
                    <em class="ico"></em>
                    @{
                        var i = 0;
                        foreach (var keyWord in article.KeyWords.Split(','))
                        {
                            if (i > 5)
                            {
                                break;
                            }
                            if (!string.IsNullOrEmpty(keyWord))
                            {
                                <a href="/Search/Index?key=@keyWord" target="_blank" class="topic-lab" topicid="3" style="background: rgb(46, 75, 107); margin: 5px;">@keyWord<i></i></a>
                                i++;
                            }
                        }
                    }

                </div>
                <span class="click-collect" onclick="bindCollect(this,@article.Id)">
                    <a><i></i>收藏</a>
                </span>
                <span class="publish-time">@article.CreateTime.ToString("yy-MM-dd HH:mm")</span>
            </div>
            <div class="articlecontent">
                @Html.Raw(article.Content)
            </div>
            <!--分享-->
            <div class="interest-share">
                @{
                    if (!string.IsNullOrEmpty(article.Company))
                    {
                        <div class="interest">
                            转载自：
                            <a href="@article.Url" target="_blank">@article.Company</a>
                        </div>
                    }
                }
            </div>
        </div>

        <!--评论区-->
        <div id="commentarea">
            @{
                Html.RenderAction("ArticleComment", "ArticleVote", article);
            }
        </div>
    </div>
    <!--右侧区域-->
    <div class="thread-right">
        @{
            if (string.IsNullOrEmpty(article.Company))  //company为空，表示是原创文章，不是抓取的
            {
                //作者信息
                Html.RenderAction("ArticleWriterInfo", "UserCenter", article);
            }
            
            //相关文章推荐
            //Html.RenderAction("RelativeArticle", "Article", article);
        }
    </div>
</div>
<div class="clear"></div>
@section scripts
{
<script src="~/Scripts/ArticleVote/articleComment.js"></script>
<script src="~/Scripts/ArticleVote/articleCommentVote.js"></script>
<script src="~/Scripts/ArticleVote/articleCollect.js"></script>
    <script type="text/templateReComment">
        <div class="reply-box">
            <textarea id="reply-content" placeholder="请发表回复，回复中不要带有侮辱国家或他人的言论。" class=""></textarea>
            <div class="button-box" style="position: relative;">
                <div class="char-limit">
                    <em>还可以输入</em> <i style="color: #2175d0;">500</i> <b>字</b>
                </div><a href="javascript:;" class="face-btn"><i></i>发表情</a>
                <a href="javascript:;" id="reply-pickfiles" class="upload-img-btn" style="z-index: 1;">
                    <i></i>发图片
                </a> <a href="javascript:;" id="pub-reply" class="blue-button">回复评论</a>
            </div>
        </div>
    </script>
}

ImPinker/ImPinker/Views/Article/MyArticle.cshtml
@using ImModel
@using ImPinker.Common
@{
    ViewBag.Title = "个人中心-EngineStart";
    var articles = (List<Article>)ViewBag.Articles;
    <link href="~/Content/usercenter.css" rel="stylesheet" />
}
<div class="dialog-layer" style="display: none;">
    <div id="dialog" style="top: 200px;">
        <p>是否要删除这篇帖子？</p>
        <div class="button-box">
            <a href="javascript:;" class="cancel" style="display: inline-block;">取消</a>
            <a href="javascript:;" class="confirm" style="border-color: rgb(233, 113, 113); background: rgb(233, 113, 113);">确定</a>
        </div>
    </div>
</div>
<div id="container" style="min-height: 557px;">
    @Html.Partial("UserCenter/UserCenter_NavPartial")
    <div class="usercenter-right">
        <div class="my-thread" style="margin-top: 0px">
            <input type="hidden" value="1">
            <input type="hidden" value="0">
            <h3 class="small-title">
                所有帖子
                <em>共有 @ViewBag.totalCount 篇</em>
                @*<div class="filter">
                        <a href="javascript:;" class="current-filter">
                            所有帖子
                            <em></em>
                        </a>
                        <ul>
                            <li><a href="/center/thread?orderid=1&amp;typeid=2">精华帖子</a></li>
                            <li><a href="/center/thread?orderid=1&amp;typeid=3">被选题收录</a></li>
                            <li><a href="/center/thread?orderid=1&amp;typeid=4">被焦点图收录</a></li>
                        </ul>
                    </div>*@
                <div class="comment-nav">
                    <a href="/Article/CreateThread" target="_blank" class="current-filter">
                        发新帖子
                        <em></em>
                    </a>
                </div>
            </h3>
            <ul class="my-thread-list">
                @{
                    if (articles != null && articles.Count > 0)
                    {
                        foreach (var article in articles)
                        {
                            var aritclestate = article.State != 1 ? (article.State == 2 ? "待审核" : "审核不通过") : "";
                            var str = article.State != 1 ? "<a href=\"javascript:;\" class=\"usercenter-blue-btn thread-modify-btn\">" + aritclestate + "</a>" : "";
                <li>
                    <a href="/Article/Index?id=@article.Id" class="img-box" target="_blank">
                        <span class="create-time">@article.CreateTime</span>
                        <img src="@ImBLL.ImageUrlHelper.GetArticleImage(article.CoverImage, 0)" class="upload">
                    </a>
                    <h5 class="thread-title">
                        <a href="/Article/Index?id=@article.Id" target="_blank">
                            @article.ArticleName
                        </a>
                    </h5>
                    <div class="thread-info">
                        <div class="thread-count">
                            <span class="click-count"><i></i>0</span>
                            <span class="comment-count"><i></i>0</span>
                            <span class="praise-count"><i></i>0</span>
                        </div>
                        <div class="button-area">
                            @Html.Raw(str)
                            <a href="/Article/UpdateThread?articleId=@article.Id" target="_blank" class="usercenter-blue-btn thread-modify-btn">修改</a>
                            <a href="javascript:;" class="usercenter-red-btn thread-delete-btn" onclick="confirmDelete(@article.Id)">删除</a>
                        </div>
                    </div>
                </li>
                        }

                    }
                    else
                    {
                <h2 style="font-size: 30px; color: #ccc; text-align: center; margin: 50px 0px;">您还没有发布过任何帖子</h2>
                    }
                }
            </ul>
            @{
                var totalCount = (double)ViewBag.totalCount;
                var pageIndex = (int)ViewBag.pageIndex;
                var pageCount = (int)ViewBag.pageCount;
                if (totalCount > pageCount)
                {
                    <div id="pageNum" style="display:block">
                        @{
                    var pages = Math.Ceiling(totalCount / pageCount);
                    if (pageIndex > 1)
                    {
                        <a href="/Article/MyArticle?pageIndex=1&pageCount=@pageCount">首页</a>
                            <a class="next" href="/Article/MyArticle?pageIndex=@(pageIndex-1)&pageCount=@pageCount">上一页</a>
                    }
                    for (var i = 1; i <= pages; i++)
                    {
                        var href = string.Format("/Article/MyArticle?pageIndex={0}&pageCount={1}", i, pageCount);
                        var classStr = pageIndex == i ? "class=current-page" : "";
                        <a @classStr href="@href">@i</a>
                    }
                    <a class="next" href="/Article/MyArticle?pageIndex=@(pageIndex+1)&pageCount=@pageCount">下一页</a>
                            <a href="/Article/MyArticle?pageIndex=@pages&pageCount=@pageCount">尾页</a>
                            <span class="jump">共 @pages 页</span>
                        }
                    </div>
                }
            }
        </div>
    </div>
</div>
@section scripts
{
    <script src="~/Scripts/Article/myArticle.js"></script>
    <script type="text/javascript">
        function confirmDelete(articleid) {
            $(".dialog-layer").show();
            $(".dialog-layer .cancel").bind('click', function () {
                $(".dialog-layer").hide();
                return;
            });
            $(".dialog-layer .confirm").bind('click', function () {
                $(".dialog-layer").hide();
                window.location.href = "/Article/DeleteThread?articleId=" + articleid;
                return true;
            });
        }
    </script>
}

ImPinker/ImPinker/Views/Article/UpdateThread.cshtml
@using ImModel
@using ImPinker.Common
@model dynamic

@{
    ViewBag.Title = "修改帖子";
    var article = (Article)ViewBag.Article;
    <link href="~/Content/thread.css" rel="stylesheet" />
    <link href="~/Scripts/webUpload/webuploader.css" rel="stylesheet" />
    <script src="~/Scripts/webUpload/webuploader.html5only.js"></script>
}

<div id="container">
    <h5 class="crumb"><em>当前位置：</em><a href="/index">个人中心</a>&gt;<a href="../">我的帖子</a>&gt;修改</h5>
    @using (Html.BeginForm("UpdateThread", "Article", FormMethod.Post))
    {
        <input type="hidden" name="ArticleId" value="@article.Id" />
        <input type="text" name="ArticleName" value="@article.ArticleName" id="threadName" style="font-size: 24px; padding: 20px ; margin-bottom: 30px; width: 100%; " />
        <div class="small-topic-article" style="padding: 0">
            <script id="contain" name="Content" type="text/plain" style="width: 100%; height: 800px;">
            </script>
        </div>
        <div id="uploader" class="wu-example">
            <!--用来存放文件信息-->
            <div class="btns">
                <div id="picker">设置封面图</div>
            </div>
            <div id="thelist" class="uploader-list"></div>
        </div>
        <img id="preview180" src="@ImBLL.ImageUrlHelper.GetArticleImage(article.CoverImage, 0)" style="width: 300px; height: 300px" />
        <input type="hidden" value="@article.CoverImage" name="Coverimage" id="imgPath" />
        <hr />
        @Html.ValidationSummary()
        <div class="topic-list">
            <input id="btn_publish" type="submit"
                   style=" background: #2175d0; clear: both; display: block; width: 1100px;
 line-height: 30px; font-size: 14px; color: #fff;  border-radius: 5px;
 text-align: center; margin: 10px auto; " value="确认修改" />
        </div>
    }
</div>

@section scripts
{
    <script src="/UeEditer/ueditor.config.js"></script>
    <script src="/UeEditer/ueditor.all.js"></script>
    <script src="/UeEditer/ueditor.parse.js"></script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="/UeEditer/lang/zh-cn/zh-cn.js"></script>
    <script src="~/Scripts/webUpload/uploadImg.js"></script>
    <script type="text/javascript">
        var content = "@Html.Raw(ViewBag.ArticleContent)";;
        $(document).ready(function () {
            var ue = UE.getEditor('contain');
            ue.ready(function () {
                ue.setContent(content);
            });

            $("#btn_publish").bind("click", function () {
                var flag = ue.hasContents();
                if (flag) {
                    var content = ue.getContent();
                    var articleName = $("#threadName").val();
                    return true;
                    $.ajax({
                        url: "/Article/CreateThread",
                        type: "post",
                        data: { name: articleName, content: content },
                        success: function (data) {
                            alert("bingo！");
                        },
                        error: function (data) {
                            alert(data);
                        }
                    });
                }
            });

            $(function () {
                $("#imgFile").change(function () {
                    ajaxFileUpload();
                });
            });
        });
    </script>
}